GeneralParams:
  num_sequences: 2
  valid_nucleotides: ['A', 'T', 'G', 'C']

ChimeraGenerator:
  mean_fragment_length: 300
  max_seqlen: 10000
  seed: 42
  output_folder: 'data'
  output_name: 'chimera_seq'
  save_format: 'fasta'
  